### PR TITLE
get bard working, demote from default. other minor UX fixups 

### LINKED ISSUE #215: zoom issues
when people click into single panes, we should zoom in the window contents by about 2-3x, and then when they click out, we should zoom it back again.

### LINKED ISSUE #218: [BUG] Unable to submit code snippets
Version: `v1.0.0-beta.5-universal.dmg`

https://github.com/smol-ai/GodMode/assets/9363272/069621a0-ca50-4c84-a914-8a48c8e8c048

### LINKED ISSUE #220: Deleting all text inside superprompt doesn't update in subprompts
Description: Deleting all text inside superprompt doesn't update in subprompts.

Steps to Reproduce:
1) Launch GodMode
2) Type something into superprompt
3) Select all text with CMD-A
4) Hit backspace

Expected behavior: 
All text is cleared from all subprompts (i.e. ChatGPT)

Actual behavior:
Text remains

Environment: macOS 13.4. GodMode (v1.0.0-beta.5)

### LINKED ISSUE #221: Toggling GodMode doesn't keep input focus consistency
**Description:** Toggling GodMode doesn't keep input focus consistency. I often will edit things in subprompts because I want to use a certain LLM for a certain task without triggering all of them (i.e. I will use one LLM for writing and another for code, depending on which one performs better in each task). When writing these LLM-specific prompts, I often quickly tab out to check or copy something in my code editor or the web and (because my input focus get changed on me) always accidentally paste into the superprompt which completely demolishes the prompt I have been crafting in the subprompt box. Additionally, because there is no undo history in the subprompt boxes, I am forced to rewrite the prompt all over again from memory.

**Steps to Reproduce:**
1) Launch GodMode
2) Type into a sub-prompt (i.e. chatGPT)
3) Toggle with universal shortcut (hide)
4) Toggle with universal shortcut (show)

**Expected behavior:** Will put your cursor into the last used input box before toggle.
**Actual behavior:** Focus is always returned to the superprompt input.

**Environment:** macOS 13.4. GodMode (1.0.0-beta.0)

### LINKED ISSUE #225: Bard Still Not Working For Me
I installed the latest AppImage. 

I am able to login to Google now. BUT...

When Bard opens, the screen is blank. With CTRL-2, it opens to a blank screen with just the usual headings. 

A test of sending input to all the AIs worked everywhere except in Bard - no response at all.

### PR DESCRIPTION
**Pull request by swyxio**
fixes bard issue seen in #225  

also  fixes #220 (@0xAsynchronous) and fixes #221

fixes #218 @alfonmga

my issues fixes #215

### CODE REVIEW

File: src/providers/bard.js [hunk 1]
```diff
@@ -90,11 +90,12 @@ class Bard extends Provider {
 	}
 
 	static getUserAgent() {
-		return 'Chrome';
+    // bard does not accept Electron mentions.
+		return 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36';
```
Comment (swyxio) [inline src/providers/bard.js]: basically this user agent string was causing the issue
